# Generated by Django 2.2.14 on 2022-04-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='price',
            new_name='etiqueta',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='tags',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='contra',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='poster',
            name='imagen',
            field=models.ImageField(default='img/post (1).JPG', upload_to=''),
        ),
    ]
