# Generated by Django 2.2.14 on 2022-04-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20220404_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='imagen',
            field=models.ImageField(default='post_1.JPG', upload_to='media/'),
        ),
    ]
